name: Generate 3D Contribution Graphic

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build-3d:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate 3D Contributions
        uses: yoshi389111/github-profile-3d-contrib@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user_name: VTG56
          theme: tokyonight
          png_out_path: profile-3d-contrib/VTG56-3d-contrib.png
          svg_out_path: profile-3d-contrib/VTG56-3d-contrib.svg

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile-3d-contrib/*
          git commit -m "chore: update 3D contribution graphic" || echo "no changes to commit"
          git push
